<template>
  <component
    :is="resolvedIcon"
    v-if="resolvedIcon"
    :class="cn('inline-block h-4 w-4 shrink-0', spin ? 'animate-spin' : '', $attrs.class ?? '')"
    :aria-hidden="decorative ? 'true' : undefined"
    :aria-label="decorative ? undefined : label"
    v-bind="iconAttrs"
  />
</template>

<script setup>
import { computed, useAttrs } from "vue";
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  Ban,
  Bell,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  CalendarDays,
  CalendarX,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlay,
  CirclePlus,
  CircleStop,
  CircleX,
  ClipboardList,
  Clock,
  Cloud,
  CloudUpload,
  Code2,
  Coffee,
  Container,
  Copy,
  Database,
  Download,
  EllipsisVertical,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCode2,
  FileInput,
  FileText,
  Filter,
  Fingerprint,
  FlaskConical,
  Folder,
  FolderOpen,
  FolderTree,
  GitBranch,
  Globe,
  Hammer,
  Hash,
  Heading,
  HeartPulse,
  Hexagon,
  History,
  House,
  Image,
  Images,
  Inbox,
  Info,
  KeyRound,
  Layers,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Menu,
  Minus,
  Monitor,
  MousePointerClick,
  Network,
  Package,
  PackageOpen,
  Pause,
  Pen,
  Pencil,
  Play,
  Plug,
  Plus,
  Power,
  Redo2,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldUser,
  SlidersHorizontal,
  Square,
  SquareCheck,
  Star,
  Tag,
  Tags,
  Terminal,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  User,
  CircleUserRound,
  UserPlus,
  Users,
  UsersRound,
  UserX,
  WandSparkles,
  Workflow,
  Wrench,
  X,
} from "lucide-vue-next";
import { cn } from "@/lib/utils";

defineOptions({ inheritAttrs: false });

const props = defineProps({
  name: { type: String, default:"" },
  label: { type: String, default:"" },
  decorative: { type: Boolean, default: true },
  spin: { type: Boolean, default: false },
});

const attrs = useAttrs();

const iconAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});

const aliases = {
  "angle-double-left": ChevronsLeft,
  "angle-double-right": ChevronsRight,
  "angle-left": ChevronLeft,
  "angle-right": ChevronRight,
  archive: Archive,
  arrow_down: ArrowDown,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  arrow_left: ArrowLeft,
  "arrow-right": ArrowRight,
  arrow_right: ArrowRight,
  "arrow-up": ArrowUp,
  arrow_up: ArrowUp,
  ban: Ban,
  bars: Menu,
  bell: Bell,
  book: BookOpen,
  box: Box,
  "box-open": PackageOpen,
  boxes: Boxes,
  broom: Eraser,
  calendar: Calendar,
  "calendar-alt": Calendar,
  "calendar-times": CalendarX,
  "calendar-week": CalendarDays,
  "chart-line": ChartLine,
  check: Check,
  "check-circle": CircleCheck,
  "check-square": SquareCheck,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-info": Info,
  clock: Clock,
  cloud: Cloud,
  "cloud-arrow-up": CloudUpload,
  "cloud-upload-alt": CloudUpload,
  code: Code2,
  "code-branch": GitBranch,
  cog: Settings,
  cogs: Settings,
  copy: Copy,
  cube: Box,
  cubes: Boxes,
  database: Database,
  desktop: Monitor,
  "diagram-project": Workflow,
  docker: Container,
  download: Download,
  edit: Pencil,
  "ellipsis-v": EllipsisVertical,
  "exchange-alt": ArrowRightLeft,
  "exclamation-circle": CircleAlert,
  "exclamation-triangle": TriangleAlert,
  "external-link-alt": ExternalLink,
  eye: Eye,
  "eye-slash": EyeOff,
  file: File,
  "file-alt": FileText,
  "file-code": FileCode2,
  "file-export": FileArchive,
  "file-import": FileInput,
  "file-lines": FileText,
  "file-upload": Upload,
  filter: Filter,
  fingerprint: Fingerprint,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-tree": FolderTree,
  gears: Settings2,
  globe: Globe,
  hammer: Hammer,
  "hand-pointer": MousePointerClick,
  hashtag: Hash,
  heading: Heading,
  heartbeat: HeartPulse,
  history: History,
  home: House,
  house: House,
  image: Image,
  images: Images,
  inbox: Inbox,
  info: Info,
  "info-circle": Info,
  java: Coffee,
  key: KeyRound,
  "layer-group": Layers,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  "list-alt": ClipboardList,
  "list-check": ListChecks,
  "list-ol": ListOrdered,
  lock: LockKeyhole,
  "log-out": LogOut,
  magic: WandSparkles,
  minus: Minus,
  network: Network,
  "network-wired": Network,
  node: Hexagon,
  "node-js": Hexagon,
  package: Package,
  "paper-plane": Send,
  pause: Pause,
  pen: Pen,
  people: Users,
  "people-group": UsersRound,
  play: Play,
  "play-circle": CirclePlay,
  plug: Plug,
  plus: Plus,
  "plus-circle": CirclePlus,
  "power-off": Power,
  "project-diagram": Workflow,
  python: FileCode2,
  "question-circle": CircleHelp,
  redo: Redo2,
  refresh: RefreshCw,
  "right-left": ArrowRightLeft,
  rocket: Rocket,
  save: Save,
  search: Search,
  server: Server,
  shield: Shield,
  "shield-alt": Shield,
  "shield-halved": ShieldCheck,
  sitemap: Workflow,
  "sliders-h": SlidersHorizontal,
  spinner: LoaderCircle,
  square: Square,
  star: Star,
  stop: Square,
  "stop-circle": CircleStop,
  sync: RefreshCw,
  "sync-alt": RefreshCw,
  tag: Tag,
  tags: Tags,
  tasks: ListChecks,
  terminal: Terminal,
  times: X,
  "times-circle": CircleX,
  trash: Trash2,
  "trash-alt": Trash2,
  undo: Undo2,
  upload: Upload,
  user: User,
  "user-circle": CircleUserRound,
  "user-plus": UserPlus,
  "user-shield": ShieldUser,
  "user-slash": UserX,
  users: Users,
  vial: FlaskConical,
  wrench: Wrench,
  x: X,
};

const directIcons = {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  Ban,
  Bell,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  CalendarDays,
  CalendarX,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlay,
  CirclePlus,
  CircleStop,
  CircleX,
  ClipboardList,
  Clock,
  Cloud,
  CloudUpload,
  Code2,
  Coffee,
  Container,
  Copy,
  Database,
  Download,
  EllipsisVertical,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCode2,
  FileInput,
  FileText,
  Filter,
  Fingerprint,
  FlaskConical,
  Folder,
  FolderOpen,
  FolderTree,
  GitBranch,
  Globe,
  Hammer,
  Hash,
  Heading,
  HeartPulse,
  Hexagon,
  History,
  House,
  Image,
  Images,
  Inbox,
  Info,
  KeyRound,
  Layers,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Menu,
  Minus,
  Monitor,
  MousePointerClick,
  Network,
  Package,
  PackageOpen,
  Pause,
  Pen,
  Pencil,
  Play,
  Plug,
  Plus,
  Power,
  Redo2,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldUser,
  SlidersHorizontal,
  Square,
  SquareCheck,
  Star,
  Tag,
  Tags,
  Terminal,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  User,
  CircleUserRound,
  UserPlus,
  Users,
  UsersRound,
  UserX,
  WandSparkles,
  Workflow,
  Wrench,
  X,
};

function toPascalCase(value) {
  return String(value ||"")
    .replace(/^icon-/,"")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

const resolvedIcon = computed(() => {
  const raw = String(props.name ||"").trim();
  if (!raw) return null;
  const normalized = raw.trim().split(/\s+/).pop();
  return aliases[normalized] || aliases[raw] || directIcons[toPascalCase(normalized)] || Circle;
});
</script>
