/** 操作日志 action → 中文名称（与后端 OperationLogger.log 的 operation 一致） */
export const OPERATION_LOG_LABELS = {
  login: "登录",
  logout: "登出",
  change_password: "修改密码",
  create_app_key: "创建 APP Key",
  delete_app_key: "删除 APP Key",
  toggle_app_key: "切换 APP Key 状态",
  create_user: "创建用户",
  update_user: "更新用户",
  delete_user: "删除用户",
  change_user_password: "修改用户密码",
  toggle_user_enable: "启用/禁用用户",
  admin_list_user_app_keys: "查看用户 APP Key",
  admin_create_user_app_key: "为用户创建 APP Key",
  admin_delete_user_app_key: "删除用户 APP Key",
  admin_toggle_user_app_key: "切换用户 APP Key",
  create_role: "创建角色",
  update_role: "更新角色",
  delete_role: "删除角色",
  clear_logs: "清理操作日志",
  save_git_config: "保存 Git 配置",
  save_registries: "保存仓库配置",
  save_config: "保存配置",
  update_system_settings: "更新系统设置",
  build: "构建镜像",
  build_from_source: "从源码构建",
  stop_build_task: "停止构建任务",
  retry_build_task: "重试构建任务",
  delete_build_task: "删除构建任务",
  cleanup_tasks: "清理构建任务",
  cleanup_exports: "清理导出文件",
  export: "导出镜像",
  stop_export_task: "停止导出任务",
  retry_export_task: "重试导出任务",
  delete_export_task: "删除导出任务",
  template_create: "创建模板",
  template_update: "更新模板",
  template_delete: "删除模板",
  docker_info_refresh: "刷新 Docker 信息",
  docker_image_delete: "删除镜像",
  docker_images_prune: "清理无用镜像",
  docker_container_start: "启动容器",
  docker_container_stop: "停止容器",
  docker_container_restart: "重启容器",
  docker_container_remove: "删除容器",
  docker_containers_prune: "清理已停止容器",
  pipeline_create: "创建流水线",
  pipeline_update: "更新流水线",
  pipeline_delete: "删除流水线",
  pipeline_run: "运行流水线",
  pipeline_run_queued: "流水线入队",
  pipeline_trigger: "Webhook 触发流水线",
  git_source_create: "创建数据源",
  git_source_update: "更新数据源",
  git_source_delete: "删除数据源",
  commit_dockerfile: "提交 Dockerfile",
  resource_package_upload: "上传资源包",
  resource_package_delete: "删除资源包",
  resource_package_edit: "编辑资源包",
  host_test_ssh: "测试 SSH 连接",
  host_add: "添加主机",
  host_update: "更新主机",
  host_delete: "删除主机",
  agent_host_add: "添加 Agent 主机",
  agent_host_approve: "批准 Agent",
  agent_host_reject: "拒绝 Agent",
  agent_host_update: "更新 Agent 主机",
  agent_host_delete: "删除 Agent 主机",
  agent_secret_create: "创建 Agent 密钥",
  agent_secret_enable: "启用 Agent 密钥",
  agent_secret_disable: "禁用 Agent 密钥",
  agent_secret_delete: "删除 Agent 密钥",
  agent_secret_update: "更新 Agent 密钥",
  deploy_task_create: "创建部署任务",
  deploy_task_update: "更新部署配置",
  deploy_task_execute: "执行部署",
  deploy_task_import: "导入部署配置",
  deploy_task_delete: "删除部署配置",
  retry_deploy_task: "重试部署任务",
  清理构建上下文: "清理构建上下文",
};

/** 筛选下拉常用操作（按分类排序） */
export const OPERATION_LOG_FILTER_OPTIONS = [
  { value: "login", label: "登录" },
  { value: "logout", label: "登出" },
  { value: "build", label: "构建镜像" },
  { value: "build_from_source", label: "从源码构建" },
  { value: "export", label: "导出镜像" },
  { value: "pipeline_create", label: "创建流水线" },
  { value: "pipeline_update", label: "更新流水线" },
  { value: "pipeline_delete", label: "删除流水线" },
  { value: "pipeline_run", label: "运行流水线" },
  { value: "deploy_task_create", label: "创建部署任务" },
  { value: "deploy_task_execute", label: "执行部署" },
  { value: "save_config", label: "保存配置" },
  { value: "save_registries", label: "保存仓库配置" },
  { value: "template_create", label: "创建模板" },
  { value: "template_update", label: "更新模板" },
  { value: "template_delete", label: "删除模板" },
  { value: "clear_logs", label: "清理操作日志" },
  { value: "create_user", label: "创建用户" },
  { value: "update_user", label: "更新用户" },
  { value: "delete_user", label: "删除用户" },
];

export function getOperationLogLabel(operation) {
  if (!operation) return "—";
  return OPERATION_LOG_LABELS[operation] || operation;
}
